db.Restaurant.find()
db.Restaurant.find( {} , { restaurant_id : 1, name : 1, borough : 1, cuisine : 1 } )
db.Restaurant.find( {} , { _id : 0, restaurant_id : 1, name : 1, borough : 1, cuisine : 1 } )
db.Restaurant.find( {} , { _id : 0, restaurant_id : 1, name : 1, borough : 1, address: {zipcode:1} })
db.Restaurant.find({borough:"Bronx"})
db.Restaurant.find({borough:"Bronx"}).limit(5).pretty()
db.Restaurant.find({borough:"Bronx"}).skip(5).limit(5)
db.Restaurant.find({"grades.score":{$gt:90}})
db.Restaurant.find({"grades.score":{$gt:80,$lt:100}})
db.Restaurant.find({"address.coord.0": {$lt:-95.754168}})
db.Restaurant.find({$and: [{"cuisine":{$ne:"American "}},{"address.coord.0":{$lt:-65.754168}},{"grades.score":{$gt:70}}]})
db.Restaurant.find({"cuisine":{$ne:"American "},"address.coord.0":{$lt:-65.754168},"grades.score":{$gt:70}})ç
db.Restaurant.find( {$and: [{"cuisine":{$ne:"American "}},{"grades.grade":"A"},{borough:{$ne:"Brooklyn"}}]}).sort({cuisine:-1})
db.Restaurant.find( {name:{$regex:/^Wil/}},{ _id : 0, restaurant_id : 1, name : 1, borough : 1, cuisine : 1,})
db.Restaurant.find( {name:{$regex:/ces$/}},{ _id : 0, restaurant_id : 1, name : 1, borough : 1, cuisine : 1,})
db.Restaurant.find( {name:{$regex:/Reg/}},{ _id : 0, restaurant_id : 1, name : 1, borough : 1, cuisine : 1,})
db.Restaurant.find( {borough:"Bronx", $or: [{"cuisine":"American "},{"cuisine":"Chinese"}]})
db.Restaurant.find( {$or: [{borough:"Bronx"},{borough:"Staten Island"},{borough:"Brooklyn"}]})
db.Restaurant.find( {$nor: [{borough:"Bronx"},{borough:"Staten Island"},{borough:"Brooklyn"}]},{_id:0,restaurant_id:1,name:1,borough:1,cuisine:1})
db.Restaurant.find({"grades.score":{$lt:10},borough:"Brooklyn"},{_id:0, restaurant_id:1, name:1, borough:1, cuisine:1 })
db.Restaurant.find({$or:[{"cuisine":"American "},{"cuisine":"Chinese"},{"cuisine":"Seafood"},{name:{$regex:/^Wil/}}]},{_id:0,restaurant_id:1,name:1,borough:1,cuisine:1})
db.Restaurant.find({$and: [{"grades.score":11},{"grades.grade":"A"},{"grades.date":{"$gte":new Date("2014-08-11T00:00:00Z")}}]},{_id:0,restaurant_id:1,name:1,grades:1})
db.Restaurant.find({$and: [{"grades.1.score":9},{"grades.1.grade":"A"},{"grades.1.date":{"$gte":new Date("2014-08-11T00:00:00Z")}}]},{_id:0,restaurant_id:1,name:1,grades:1})
db.Restaurant.find({"address.coord.1":{$gt:42,$lt:52}},{_id:0,restaurant_id:1,name:1,address:1})
db.Restaurant.find().sort({name:1})
db.Restaurant.find().sort({name:-1})
db.Restaurant.find({},{_id:0,borough:1,cuisine:1,name:1}).sort({cuisine:1,borough:-1})
db.Restaurant.find({"address.street":{$exists:false}}).count()>0
db.Restaurant.find( {"address.coord":{$type:"double"} } )

db.Restaurant.find( {name:{$regex:/mon/}},{ _id : 0, name : 1, borough : 1, "address.coord":1, cuisine : 1,})
db.Restaurant.find( {name:{$regex:/^Mad/}},{ _id : 0, name : 1, borough : 1, "address.coord":1, cuisine : 1,})